name: GitHub Release Notifier
description: "Notify repositories about releases using a GitHub App"
branding:
  icon: "rss"
  color: purple
inputs:
  app_id:
    description: "Your GitHub App's App ID"
    required: true
  private_key:
    description: "Your GitHub Private Key"
    required: true
  dispatch_event_type:
    description: "The name of the repository dispatch event, see https://git.io/JTpRo. Defaults to '[owner]/[repo] release', e.g. 'gr2m/release-notifier-action release'"
    required: false
  embed_payload_as_json_string:
    description: "Instead of event_payload, use a syntetic event object with payload embedded as JSON string, e.g. '{event_payload:<payload_as_json_string>}"
    required: false
runs:
  using: "node16"
  main: "dist/index.js"
