"on":
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - dependabot/npm_and_yarn/*
name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16 # starting with Node 18, `nock` no longer intercepts requests.
      - run: npm ci
      - run: npm test
  readmeExample:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - run: npm ci
      - run: npm run build
      - uses: ./
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
        env:
          TEST_GITHUB_EVENT_PATH: ${{ github.workspace }}/test/new-release/event.json
